# Generated by Django 4.2.5 on 2023-11-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
