# Generated by Django 4.2.5 on 2023-11-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0003_remove_userprofile_city_remove_userprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='DOB',
        ),
    ]
