# Generated by Django 4.2.5 on 2023-11-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0011_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='-', upload_to='post images'),
        ),
    ]
