# Generated by Django 4.2.7 on 2023-11-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0016_alter_post_id_alter_post_image_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post images'),
        ),
    ]
