# Generated by Django 4.2.5 on 2023-11-30 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0017_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('connection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
