# Generated by Django 4.2.7 on 2023-12-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0020_remove_comments_id_comments_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
    ]
