# Generated by Django 4.2.7 on 2023-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddi', '0022_remove_comments_post_id_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments1',
            field=models.ManyToManyField(related_name='comments', to='buddi.comments'),
        ),
    ]
