# Generated by Django 4.2.7 on 2023-12-06 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddi', '0024_remove_comments_username_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.AddField(
            model_name='followers',
            name='followed',
            field=models.ForeignKey(default=777, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.ForeignKey(default=777, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
